package com.project.toko.detailScreen.ui.detailScreen.mainPage

import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.background
import androidx.compose.foundation.combinedClickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewModelScope
import coil.ImageLoader
import coil.compose.rememberAsyncImagePainter
import coil.request.ImageRequest
import coil.size.Size
import com.google.accompanist.swiperefresh.rememberSwipeRefreshState
import com.project.toko.core.ui.animations.LoadingAnimation
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.AddToFavorites
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.DisplayJapAndEnglishTitles
import com.project.toko.detailScreen.ui.detailScreen.sideContent.castList.DisplayCast
import com.project.toko.detailScreen.ui.detailScreen.mainPage.customVisuals.DisplayCustomGenreBoxes
import com.project.toko.detailScreen.ui.detailScreen.sideContent.staffList.DisplayStaff
import com.project.toko.detailScreen.ui.viewModel.DetailScreenViewModel
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.DisplayPicture
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.DisplayTitle
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.ExpandableRelated
import com.project.toko.core.ui.expandableText.ExpandableText
import com.project.toko.core.ui.pullToRefpresh.PullToRefreshLayout
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.FavoritesLine
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.MembersLine
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.PopularityLine
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.RankedLine
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.AnimeAlike
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.ScoreByNumber
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.ScoreLabel
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.ScoreNumber
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.ShowBackground
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.ShowMoreInformation
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.ShowPictureAlbum
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.YearTypeEpisodesTimeStatusStudio
import com.project.toko.detailScreen.ui.detailScreen.mainPage.custom.youtubePlayer.YoutubePlayer
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext



