package com.example.animeapp.domain.exampleModels
import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName
data class Data(
     @SerializedName("aired") val aired: com.example.animeapp.domain.exampleModels.Aired,
     @SerializedName("airing") val airing: Boolean,
     @SerializedName("approved") val approved: Boolean,
     @SerializedName("background") val background: String,
     @SerializedName("broadcast") val broadcast: com.example.animeapp.domain.exampleModels.Broadcast,
     @SerializedName("demographics") val demographics: List<com.example.animeapp.domain.exampleModels.Demographic>,
     @SerializedName("duration") val duration: String,
     @SerializedName("episodes") val episodes: Int,
     @SerializedName("explicit_genres") val explicit_genres: List<com.example.animeapp.domain.exampleModels.ExplicitGenre>,
     @SerializedName("favorites") val favorites: Int,
     @SerializedName("genres") val genres: List<com.example.animeapp.domain.exampleModels.Genre>,
     @SerializedName("images") val images: com.example.animeapp.domain.exampleModels.Images,
     @SerializedName("licensors") val licensors: List<com.example.animeapp.domain.exampleModels.Licensor>,
     @SerializedName("mal_id") val mal_id: Int,
     @SerializedName("members") val members: Int,
     @SerializedName("popularity") val popularity: Int,
     @SerializedName("producers") val producers: List<com.example.animeapp.domain.exampleModels.Producer>,
     @SerializedName("rank") val rank: Int,
     @SerializedName("rating") val rating: String,
     @SerializedName("score") val score: Int,
     @SerializedName("scored_by") val scored_by: Int,
     @SerializedName("season") val season: String,
     @SerializedName("source") val source: String,
     @SerializedName("status") val status: String,
     @SerializedName("studios") val studios: List<com.example.animeapp.domain.exampleModels.Studio>,
     @SerializedName("synopsis") val synopsis: String,
     @SerializedName("themes") val themes: List<com.example.animeapp.domain.exampleModels.Theme>,
     @SerializedName("title") val title: String,
     @SerializedName("title_english") val title_english: String,
     @SerializedName("title_japanese") val title_japanese: String,
     @SerializedName("title_synonyms") val title_synonyms: List<String>,
     @SerializedName("titles") val titles: List<com.example.animeapp.domain.exampleModels.Title>,
     @SerializedName("trailer") val trailer: com.example.animeapp.domain.exampleModels.Trailer,
     @SerializedName("type") val type: String,
     @SerializedName("url") val url: String,
     @SerializedName("year") val year: Int
)