package com.project.toko.homeScreen.model.linkChangerModel


import androidx.compose.runtime.MutableState
import androidx.compose.runtime.mutableStateOf


data class Genre(
    val name: String,
    val id: Int,
    val isSelected: MutableState<Boolean> = mutableStateOf(false)
)

fun getGenres(): List<Genre> {
    return listOf(
        Genre("Action", 1),
        Genre("Adventure", 2),
        Genre("Racing", 3),
        Genre("Comedy", 4),
        Genre("Avant Garde", 5),
        Genre("Mythology", 6),
        Genre("Mystery", 7),
        Genre("Drama", 8),
        Genre("Ecchi", 9),
        Genre("Fantasy", 10),
        Genre("Strategy Game", 11),
        Genre("Hentai", 12),
        Genre("Historical", 13),
        Genre("Horror", 14),
        Genre("Kids", 15),
        Genre("Martial Arts", 17),
        Genre("Mecha", 18),
        Genre("Music", 19),
        Genre("Parody", 20),
        Genre("Samurai", 21),
        Genre("Romance", 22),
        Genre("School", 23),
        Genre("Sci-Fi", 24),
        Genre("Shoujo", 25),
        Genre("Girls Love", 26),
        Genre("Shounen", 27),
        Genre("Boys Love", 28),
        Genre("Space", 29),
        Genre("Sports", 30),
        Genre("Super Power", 31),
        Genre("Vampire", 32),
        Genre("Harem", 35),
        Genre("Slice of Life", 36),
        Genre("Supernatural", 37),
        Genre("Military", 38),
        Genre("Detective", 39),
        Genre("Psychological", 40),
        Genre("Suspense", 41),
        Genre("Seinen", 42),
        Genre("Josei", 43),
        Genre("Award Winning", 46),
        Genre("Gourmet", 47),
        Genre("Workplace", 48),
        Genre("Erotica", 49),
        Genre("Adult Cast", 50),
        Genre("Anthropomorphic", 51),
        Genre("CGDCT", 52),
        Genre("Childcare", 53),
        Genre("Combat Sports", 54),
        Genre("Delinquents", 55),
        Genre("Educational", 56),
        Genre("Gag Humor", 57),
        Genre("Gore", 58),
        Genre("High Stakes Game", 59),
        Genre("Idols (Female)", 60),
        Genre("Idols (Male)", 61),
        Genre("Isekai", 62),
        Genre("Iyashikei", 63),
        Genre("Love Polygon", 64),
        Genre("Magical Sex Shift", 65),
        Genre("Mahou Shoujo", 66),
        Genre("Medical", 67),
        Genre("Organized Crime", 68),
        Genre("Otaku Culture", 69),
        Genre("Performing Arts", 70),
        Genre("Pets", 71),
        Genre("Reincarnation", 72),
        Genre("Reverse Harem", 73),
        Genre("Romantic Subtext", 74),
        Genre("Showbiz", 75),
        Genre("Survival", 76),
        Genre("Team Sports", 77),
        Genre("Time Travel", 78),
        Genre("Video Game", 79),
        Genre("Visual Arts", 80),
        Genre("Crossdressing", 81)
    )
}
